version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    env_file:
      - .env 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3316:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: golang-backend
    restart: always
    env_file:
      - .env 
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: react-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    depends_on:
      - backend  


volumes:
  db_data:
